' Auto-split by V3 modularization
Sub GenerateASM(ByVal fn As String)
    outFF=FreeFile:Open fn For Output As #outFF
    EmitHeader():EmitStringInitializers():EmitDataInitializers()
    For i As Long=1 To instrCount:If needLabel(i) Then EmitLine "__ux_ip_"+LTrim(Str(i))+":"
        EmitInstr i
    Next
    EmitFooter():Close #outFF
End Sub

Sub EmitLine(ByVal s As String):Print #outFF,s:End Sub

Sub EmitHeader()
    EmitLine "; generated by "+UXM_VERSION
    EmitLine "default rel":EmitLine "global uxm_entry":EmitLine "global ux_mem":EmitLine "global ux_status":EmitLine "global ux_flags":EmitLine "global ux_ptr":EmitLine "global ux_sp"
    EmitLine "global ux_cell_bits":EmitLine "global ux_cell_bytes":EmitLine "global ux_tape_cells":EmitLine "global ux_stack_cells":EmitLine "global ux_data_cells":EmitLine "global ux_stack_offset":EmitLine "global ux_data_offset"
    EmitLine "extern ux_putc":EmitLine "extern ux_getc":EmitLine "extern ux_print_data_string":EmitLine "extern ux_meta_call_ex":EmitLine "extern ux_runtime_error"
    EmitLine "%define UXM_TOTAL_BYTES 65536":EmitLine "%define TAPE_CELLS "+LTrim(Str(tapeCells)):EmitLine "%define STACK_CELLS "+LTrim(Str(stackCells)):EmitLine "%define DATA_CELLS "+LTrim(Str(dataCells)):EmitLine "%define STACK_OFFSET "+LTrim(Str(stackOffset)):EmitLine "%define DATA_OFFSET "+LTrim(Str(dataOffset)):EmitLine "%define CELL_BITS "+LTrim(Str(cellBits)):EmitLine "%define CELL_BYTES "+LTrim(Str(CellSize()))
    EmitLine "%define FLAG_Z 1":EmitLine "%define FLAG_C 2":EmitLine "%define FLAG_O 4":EmitLine "%define FLAG_S 8":EmitLine "%define FLAG_SGN 16":EmitLine "%define FLAG_END 32":EmitLine "%define FLAG_WILD 64":EmitLine "%define FLAG_BND 128"
    EmitLine "section .bss":EmitLine "align 16":EmitLine "ux_mem: resb UXM_TOTAL_BYTES":EmitLine "ux_status: resb 1":EmitLine "ux_flags: resw 1":EmitLine "ux_ptr: resq 1":EmitLine "ux_sp: resq 1":EmitLine "ux_cell_bits: resd 1":EmitLine "ux_cell_bytes: resd 1":EmitLine "ux_tape_cells: resd 1":EmitLine "ux_stack_cells: resd 1":EmitLine "ux_data_cells: resd 1":EmitLine "ux_stack_offset: resd 1":EmitLine "ux_data_offset: resd 1"
    EmitLine "section .text":EmitLine "uxm_entry:":EmitLine "    push rbp":EmitLine "    mov rbp, rsp":EmitLine "    push rbx":EmitLine "    push r12":EmitLine "    push r13":EmitLine "    push r14":EmitLine "    push r15":EmitLine "    sub rsp, 40":EmitLine "    mov dword [ux_cell_bits], CELL_BITS":EmitLine "    mov dword [ux_cell_bytes], CELL_BYTES":EmitLine "    mov dword [ux_tape_cells], TAPE_CELLS":EmitLine "    mov dword [ux_stack_cells], STACK_CELLS":EmitLine "    mov dword [ux_data_cells], DATA_CELLS":EmitLine "    mov dword [ux_stack_offset], STACK_OFFSET":EmitLine "    mov dword [ux_data_offset], DATA_OFFSET":EmitLine "    lea r12, [ux_mem]":EmitLine "    lea r13, [ux_mem + STACK_OFFSET]":EmitLine "    xor rbx, rbx":EmitLine "    xor r14, r14":EmitLine "    mov qword [ux_ptr], rbx":EmitLine "    mov qword [ux_sp], r14":EmitLine "    mov byte [ux_status], 0":EmitLine "    mov word [ux_flags], "+LTrim(Str(flags And &HFFFF))
End Sub

Sub EmitStringInitializers()
    Dim i As Long,j As Long,bo As Long,ch As Long
    For i=1 To strCount
        For j=1 To Len(strDef(i).txt)
            ch=Asc(Mid(strDef(i).txt,j,1)) And &HFF:bo=dataOffset+(strDef(i).startCell+j-1)*CellSize():EmitLine "    mov "+MemSizePrefix()+" [ux_mem + "+LTrim(Str(bo))+"], "+LTrim(Str(ch))
        Next
        bo=dataOffset+(strDef(i).startCell+Len(strDef(i).txt))*CellSize():EmitLine "    mov "+MemSizePrefix()+" [ux_mem + "+LTrim(Str(bo))+"], 0"
    Next
End Sub

Sub EmitInstr(ByVal i As Long)
    Select Case progInstr(i).op
    Case OP_RIGHT:If progInstr(i).amount=1 Then EmitLine "    inc rbx" Else EmitLine "    add rbx, "+LTrim(Str(progInstr(i).amount))
    Case OP_LEFT:If progInstr(i).amount=1 Then EmitLine "    dec rbx" Else EmitLine "    sub rbx, "+LTrim(Str(progInstr(i).amount))
    Case OP_INC:EmitAddrLoad progInstr(i).addrKind,progInstr(i).addrVal,progInstr(i).addrVal2,"rax":EmitLine "    add rax, "+LTrim(Str(progInstr(i).amount)):EmitAddrStore progInstr(i).addrKind,progInstr(i).addrVal,progInstr(i).addrVal2,"rax":EmitSetFlagsFromRAX()
    Case OP_DEC:EmitAddrLoad progInstr(i).addrKind,progInstr(i).addrVal,progInstr(i).addrVal2,"rax":EmitLine "    sub rax, "+LTrim(Str(progInstr(i).amount)):EmitAddrStore progInstr(i).addrKind,progInstr(i).addrVal,progInstr(i).addrVal2,"rax":EmitSetFlagsFromRAX()
    Case OP_SET:EmitLine "    mov rax, "+LTrim(Str(progInstr(i).amount)):EmitAddrStore progInstr(i).addrKind,progInstr(i).addrVal,progInstr(i).addrVal2,"rax":EmitSetFlagsFromRAX()
    Case OP_CLEAR:EmitLine "    xor rax, rax":EmitAddrStore progInstr(i).addrKind,progInstr(i).addrVal,progInstr(i).addrVal2,"rax":EmitSetFlagsFromRAX()
    Case OP_PUTC:EmitAddrLoad progInstr(i).addrKind,progInstr(i).addrVal,progInstr(i).addrVal2,"rax":EmitLine "    mov ecx, eax":EmitLine "    call ux_putc"
    Case OP_GETC:EmitLine "    call ux_getc":EmitAddrStore progInstr(i).addrKind,progInstr(i).addrVal,progInstr(i).addrVal2,"rax":EmitSetFlagsFromRAX()
    Case OP_PUSH:EmitLine "    cmp r14, STACK_CELLS":EmitLine "    jae __ux_err_stack_over":EmitAddrLoad progInstr(i).addrKind,progInstr(i).addrVal,progInstr(i).addrVal2,"rax":If cellBits=8 Then EmitLine "    mov byte [r13+r14], al" Else : If cellBits=16 Then EmitLine "    mov word [r13+r14*2], ax" Else EmitLine "    mov dword [r13+r14*4], eax":EmitLine "    inc r14"
    Case OP_POP:EmitLine "    cmp r14,0":EmitLine "    je __ux_err_stack_under":EmitLine "    dec r14":If cellBits=8 Then EmitLine "    movzx rax, byte [r13+r14]" Else : If cellBits=16 Then EmitLine "    movzx rax, word [r13+r14*2]" Else EmitLine "    mov eax, dword [r13+r14*4]":EmitAddrStore progInstr(i).addrKind,progInstr(i).addrVal,progInstr(i).addrVal2,"rax":EmitSetFlagsFromRAX()
    Case OP_META:EmitMetaCall progInstr(i).metaId,progInstr(i).metaDyn
    Case OP_PRINT_STRING:Dim idx As Long=FindString(progInstr(i).amount):EmitLine "    mov ecx, "+LTrim(Str(strDef(idx).startCell)):EmitLine "    mov edx, CELL_BITS":EmitLine "    call ux_print_data_string"
    Case OP_LOOP_BEG:EmitLine "__ux_loop_beg_"+LTrim(Str(i))+":":EmitAddrLoad ADDR_T,0,0,"rax":EmitLine "    cmp rax,0":EmitLine "    je __ux_loop_end_"+LTrim(Str(i))
    Case OP_LOOP_END:EmitLine "    jmp __ux_loop_beg_"+LTrim(Str(progInstr(i).mate)):EmitLine "__ux_loop_end_"+LTrim(Str(progInstr(i).mate))+":"
    Case OP_BRANCH:EmitBranch i
    Case OP_STATUS:EmitLine "    movzx rax, byte [ux_status]":EmitAddrStore progInstr(i).addrKind,progInstr(i).addrVal,progInstr(i).addrVal2,"rax"
    Case Else:EmitLine "    nop"
    End Select
End Sub

Sub EmitAddrLoad(ByVal ak As Long, ByVal av As Long, ByVal av2 As Long, ByVal regName As String)
    EmitAddrPtr ak,av,av2,"r11":If cellBits=8 Then EmitLine "    movzx "+regName+", byte [r11]" Else : If cellBits=16 Then EmitLine "    movzx "+regName+", word [r11]" Else EmitLine "    mov eax, dword [r11]"
End Sub

Sub EmitAddrStore(ByVal ak As Long, ByVal av As Long, ByVal av2 As Long, ByVal regName As String)
    EmitAddrPtr ak,av,av2,"r11":If cellBits=8 Then EmitLine "    mov byte [r11], "+Reg8(regName) Else : If cellBits=16 Then EmitLine "    mov word [r11], "+Reg16(regName) Else EmitLine "    mov dword [r11], "+Reg32(regName)
End Sub

Sub EmitAddrPtr(ByVal ak As Long, ByVal av As Long, ByVal av2 As Long, ByVal outReg As String)
    Select Case ak
    Case ADDR_T:If cellBits=8 Then EmitLine "    lea "+outReg+", [r12+rbx]" Else : If cellBits=16 Then EmitLine "    lea "+outReg+", [r12+rbx*2]" Else EmitLine "    lea "+outReg+", [r12+rbx*4]"
    Case ADDR_T_REL:EmitLine "    mov r10, rbx":If av>=0 Then EmitLine "    add r10, "+LTrim(Str(av)) Else EmitLine "    sub r10, "+LTrim(Str(Abs(av))):If cellBits=8 Then EmitLine "    lea "+outReg+", [r12+r10]" Else : If cellBits=16 Then EmitLine "    lea "+outReg+", [r12+r10*2]" Else EmitLine "    lea "+outReg+", [r12+r10*4]"
    Case ADDR_T_ABS:EmitLine "    lea "+outReg+", [r12+"+LTrim(Str(av*CellSize()))+"]"
    Case ADDR_D_ABS:EmitLine "    lea "+outReg+", [r12+DATA_OFFSET+"+LTrim(Str(av*CellSize()))+"]"
    Case ADDR_S_ABS:EmitLine "    lea "+outReg+", [r13+"+LTrim(Str(av*CellSize()))+"]"
    Case ADDR_D_AT_T_REL:EmitAddrLoad ADDR_T,0,0,"rax":If av2>=0 Then EmitLine "    add rax, "+LTrim(Str(av2)) Else EmitLine "    sub rax, "+LTrim(Str(Abs(av2))):If cellBits=8 Then EmitLine "    lea "+outReg+", [r12+DATA_OFFSET+rax]" Else : If cellBits=16 Then EmitLine "    lea "+outReg+", [r12+DATA_OFFSET+rax*2]" Else EmitLine "    lea "+outReg+", [r12+DATA_OFFSET+rax*4]"
    Case ADDR_D_AT_TBASE_REL:EmitAddrLoad ADDR_T_REL,av,0,"rax":If av2>=0 Then EmitLine "    add rax, "+LTrim(Str(av2)) Else EmitLine "    sub rax, "+LTrim(Str(Abs(av2))):If cellBits=8 Then EmitLine "    lea "+outReg+", [r12+DATA_OFFSET+rax]" Else : If cellBits=16 Then EmitLine "    lea "+outReg+", [r12+DATA_OFFSET+rax*2]" Else EmitLine "    lea "+outReg+", [r12+DATA_OFFSET+rax*4]"
    Case Else:EmitLine "    lea "+outReg+", [r12+rbx]"
    End Select
End Sub

Sub EmitSetFlagsFromRAX()
    Dim id As Long
    id=NewAsmId()
    EmitLine "    push rax"
    EmitLine "    mov dx, word [ux_flags]"
    EmitLine "    and dx, 0FFF0h"
    EmitLine "    cmp rax, 0"
    EmitLine "    jne __ux_noz_"+LTrim(Str(id))
    EmitLine "    or dx, FLAG_Z"
    EmitLine "__ux_noz_"+LTrim(Str(id))+":"
    Select Case cellBits
    Case 8
        EmitLine "    test al, 80h"
    Case 16
        EmitLine "    test ax, 8000h"
    Case Else
        EmitLine "    test eax, 80000000h"
    End Select
    EmitLine "    jz __ux_nos_"+LTrim(Str(id))
    EmitLine "    or dx, FLAG_S"
    EmitLine "__ux_nos_"+LTrim(Str(id))+":"
    EmitLine "    mov word [ux_flags], dx"
    EmitLine "    pop rax"
End Sub

Sub EmitMetaCall(ByVal id As Long, ByVal dyn As Long)
    EmitLine "    mov qword [ux_ptr], rbx":EmitLine "    mov qword [ux_sp], r14":If dyn Then EmitAddrLoad ADDR_T,0,0,"rax":EmitLine "    mov ecx, eax" Else EmitLine "    mov ecx, "+LTrim(Str(id))
    EmitLine "    lea rdx, [ux_mem]":EmitLine "    call ux_meta_call_ex":EmitLine "    mov rbx, qword [ux_ptr]":EmitLine "    mov r14, qword [ux_sp]"
End Sub

Sub EmitBranch(ByVal i As Long)
    Dim t As Long:t=progInstr(i).brTarget:EmitLine "    ; branch -> "+Str(t)
    Select Case progInstr(i).brCond
    Case BR_ALWAYS:EmitLine "    jmp __ux_ip_"+LTrim(Str(t))
    Case BR_CUR_NZ:EmitAddrLoad ADDR_T,0,0,"rax":EmitLine "    cmp rax,0":EmitLine "    jne __ux_ip_"+LTrim(Str(t))
    Case BR_CUR_Z:EmitAddrLoad ADDR_T,0,0,"rax":EmitLine "    cmp rax,0":EmitLine "    je __ux_ip_"+LTrim(Str(t))
    Case BR_Z_SET:EmitLine "    test word [ux_flags], FLAG_Z":EmitLine "    jnz __ux_ip_"+LTrim(Str(t))
    Case BR_Z_CLR:EmitLine "    test word [ux_flags], FLAG_Z":EmitLine "    jz __ux_ip_"+LTrim(Str(t))
    Case BR_C_SET:EmitLine "    test word [ux_flags], FLAG_C":EmitLine "    jnz __ux_ip_"+LTrim(Str(t))
    Case BR_C_CLR:EmitLine "    test word [ux_flags], FLAG_C":EmitLine "    jz __ux_ip_"+LTrim(Str(t))
    Case BR_O_SET:EmitLine "    test word [ux_flags], FLAG_O":EmitLine "    jnz __ux_ip_"+LTrim(Str(t))
    Case BR_O_CLR:EmitLine "    test word [ux_flags], FLAG_O":EmitLine "    jz __ux_ip_"+LTrim(Str(t))
    Case BR_S_SET:EmitLine "    test word [ux_flags], FLAG_S":EmitLine "    jnz __ux_ip_"+LTrim(Str(t))
    Case BR_S_CLR:EmitLine "    test word [ux_flags], FLAG_S":EmitLine "    jz __ux_ip_"+LTrim(Str(t))
    Case Else:EmitLine "    ; unknown branch condition"
    End Select
End Sub

Sub EmitFooter()
    EmitLine "__ux_ok_exit:":EmitLine "    add rsp,40":EmitLine "    pop r15":EmitLine "    pop r14":EmitLine "    pop r13":EmitLine "    pop r12":EmitLine "    pop rbx":EmitLine "    pop rbp":EmitLine "    ret":EmitLine "__ux_err_stack_over:":EmitLine "    mov ecx,11":EmitLine "    call ux_runtime_error":EmitLine "    jmp __ux_ok_exit":EmitLine "__ux_err_stack_under:":EmitLine "    mov ecx,12":EmitLine "    call ux_runtime_error":EmitLine "    jmp __ux_ok_exit"
End Sub


Function CellSize() As Long
    If cellBits=8 Then
        Return 1
    ElseIf cellBits=16 Then
        Return 2
    Else
        Return 4
    End If
End Function

Function MemSizePrefix() As String
    If cellBits=8 Then
        Return "byte"
    ElseIf cellBits=16 Then
        Return "word"
    Else
        Return "dword"
    End If
End Function

Function Reg8(ByVal r As String) As String
    If LCase(r)="rax" Then
        Return "al"
    End If
    Return "al"
End Function

Function Reg16(ByVal r As String) As String
    If LCase(r)="rax" Then
        Return "ax"
    End If
    Return "ax"
End Function

Function Reg32(ByVal r As String) As String
    If LCase(r)="rax" Then
        Return "eax"
    End If
    Return "eax"
End Function

Function NewAsmId() As Long
    asmLabelCounter+=1
    Return asmLabelCounter
End Function



